version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - travel-network
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - travel-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - travel-network

networks:
  travel-network:
    driver: bridge
